### PR TITLE
[WIP] rename 'contracts' to 'offers'

### PR DESCRIPTION
**Pull request by ssa3512**
Short term fix for #191 while it is determined what to use instead

### CODE REVIEW

**Comment by aleitner** [comment]
I don't see the benefit of rnaming this to offers. Won't people still be just as confused as to what this means?

**Comment by ssa3512** [comment]
We need to figure out something to do with this as it is causing confusion for users. See #191

**Comment by aleitner** [comment]
remove wip and I'll merge

**Comment by aleitner** [comment]
Also something to think about is offers accepted vs offers that have received data

**Pull request closed without merging**
