### PR TITLE
Use bugfix version of 'daemon'

### LINKED ISSUE #277: make it work in node 8
Upon starting daemon with node 8 you are greeted with

```
TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:401:11)
    at Object.exports.spawn (child_process.js:488:38)
    at Function.module.exports.daemon (C:\Users\Felix\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\daemon\index.js:50:31)
    at module.exports (C:\Users\Felix\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\daemon\index.js:25:20)
    at utils.checkDaemonRpcStatus (C:\Users\Felix\AppData\Roaming\npm\node_modules\storjshare-daemon\bin\storjshare-daemon.js:54:7)
    at Socket.<anonymous> (C:\Users\Felix\AppData\Roaming\npm\node_modules\storjshare-daemon\lib\utils.js:216:5)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

This is due to a bug in [daemon](https://www.npmjs.com/package/daemon), specifically [this one](https://github.com/indexzero/daemon.node/issues/41).

As you can see the fix is easy but the maintainer seems inactive and doesn't merge the PR.

I propose to change the following in `package.json` to enable users to use node 8 if they feel like it:

```diff
-    "daemon": "^1.1.0",
+    "daemon": "github:zipang/daemon.node#48d0977c26fb3a6a44ae99aae3471b9d5a761085",
```

### PR DESCRIPTION
**Pull request by felixbrucker**
Fixes #277

### CODE REVIEW

**Comment by felixbrucker** [comment]
As in less than a week the new LTS starts, i hope to get this merged before that, see: https://github.com/nodejs/Release#release-schedule1

**Comment by tempestb** [comment]
Zipang's branch is indeed one change, but it is one change to indexzero's branch.   You would be inheriting indexzero's branch here.  You need to make a fork of slashed's daemon node, and implement the cwd change itself, and then link to that branch so that you aren't inheriting indexzero's branch.

**Comment by felixbrucker** [comment]
indexzero's branch is the one with the npm module currently used by storj (and everyone else who uses npm), the original repo is not used anywhere

**Comment by tempestb** [comment]
Really?  Seems strange then that they are saying nobody should use it if they aren't on 8.   But ok...

**Comment by felixbrucker** [comment]
I found the quote you keep referring to, it says: `0.8` not `8`, node 0.8 is from 2013

**Comment by tempestb** [comment]
Ah, ok, my bad then.  Sorry FB.

**Comment by littleskunk** [comment]
Looks good to me.

**Pull request merged**
