### PR TITLE
Add the packaging metadata to build the storjshare snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

snaps are the new packaging format we are developing here at ubuntu, for the secure installation of apps in linux distributions without distro maintainers as intermediaries. So you can push the snap to the store and make it easily installable by all the Ubuntu users. You can read more about it at https://snapcraft.io/

To try this in Ubuntu xenial or later:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/storjshare-daemon
    $ cd storjshare-daemon
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

(dangerous because the snap you build yourself doesn't come signed from the trusted store. Once you push it to the store, your users will just have to do `$ sudo snap install storjshare`)

I think my teammate Alan tried to contact you some weeks ago, but I decided to insist when I took a deeper look at your project. It's very very interesting, and I think the Ubuntu users would love to have it available in a secure way, without having to wget | bash. For you, I think that snaps are a great fit because you can have continuous delivery to the distro on your own schedule without complicated packaging rules and because the snap will run fully confined. When people share resources on the internet it's really important to make sure that the application can't misbehave and expose parts that they didn't want to share, and you get that for free with snaps. Finally, for us this would be great because your use case is one of the most interesting ones that we want to support, and your feedback will help us assigning priorities for our future releases.

Everybody wins :) And it was so simple to snap that I thought you might want to give it a try. If you like it, snapping the GUI and the bridge should be also this simple.

Any comments or questions, please let me know.

**Comment by bookchin** [comment]
Thanks for this! Give me a short while to review and familiarize myself with snaps so I fully understand how this all works.

**Comment by elopio** [comment]
Thanks for merging it @bookchin!
Here are the steps to push your snap to the store: https://snapcraft.io/docs/build-snaps/publish
Once you have an initial version in the edge channel we could make a call for testing in the ubuntu community to make sure that it's ready for a wider audience.

It would be great if we could meet in a hangout or something to talk about your projects and snapcraft. Do you have some time to chat?

pura vida

**Comment by bookchin** [comment]
@elopio sure I'd be happy to chat. Send me an email at gordonh@member.fsf.org

**Pull request merged**
